### PR TITLE
docs: describe new container image

### PR DESCRIPTION
**Pull request by clementnuss**
some doc, if you want to use that for the new container images:)

### CODE REVIEW

**Comment by clementnuss** [comment]
also one last point: you might need to change the package visibility once you're done building it. I've already had packages that were by default published as private packages.

edit: well it seems you stumbled upon something like that !
https://github.com/ahrtr/etcd-defrag/actions/runs/6393396273/job/17352549878#step:5:17

**Comment by ahrtr** [comment]
can you please verify whether you can pull the image?

```
docker pull ghcr.io/ahrtr/etcd-defrag:v0.4.0
```

**Comment by clementnuss** [comment]
```bash
🕙 16:13:31  ❯ docker run --rm ghcr.io/ahrtr/etcd-defrag:v0.4.0 --version
etcd-defrag Version: v0.4.0
Git SHA: b1e7e709ca00fa2b1c25012eedfadd58a7c3b2b9
Go Version: go1.20.8
Go OS/Arch: linux/arm64
```

perfect! thanks :)

**Comment by ahrtr** [comment]
thx

**Pull request merged**
